name = "ShinGroupIO"
uuid = "64b85ef0-73f0-46f0-9fe8-0c3edc37abe9"
authors = ["Sungho Shin <sushin@mit.edu>"]
version = "0.1.0"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[compat]
FileWatching = "1.11.0"
Git = "1.4.0"
LiveServer = "1.4.0"
