name: build

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - name: Install package dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'
      - name: Build website
        run: |
          julia --project=. -e 'using ShinIO; ShinIO.build()'
