name: build

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build website
        run: |
          /home/action-runner/.juliaup/bin/julia --project=. -e "using ShinGroupIO; ShinGroupIO.deploy(; dev = ${{ github.event_name == 'pull_request' }})"
